structure         input/AmtB-system.psf
###coordinates        input/start%d.pdb

paraTypeCharmm	    on
parameters          par_all27_prot_lipid_cmap.inp
parameters          toppar_amines.str


# Force-Field Parameters
exclude             scaled1-4
1-4scaling          1.0
cutoff              12.
switching           on
##vdwForceSwitching   on
switchdist          10.
pairlistdist        13.5


# Integrator Parameters
timestep            1.0  ;# 1fs/step (only if needed to finish quickly)
rigidBonds          water  
nonbondedFreq       2
fullElectFrequency  4  
stepspercycle       20


# Constant Temperature Control
langevin            on    ;# do langevin dynamicsgmail.google.com
langevinDamping     1     ;# damping coefficient (gamma) of 5/ps
langevinTemp        $temperature
langevinHydrogen    off    ;# don't couple langevin bath to hydrogens

# Periodic Boundary Conditions  
#cellBasisVector1   61.5    0.   0.
#cellBasisVector2     0.   61.5   0.
#cellBasisVector3     0.    0    71.5
#cellOrigin        -16.06 -14.75 -12

wrapAll             on

# PME (for full-system periodic electrostatics)
PME                 yes
PMEGridSpacing      1.0

# Constant Pressure Control (variable volume)
useGroupPressure      no ;# needed for rigidBonds
useFlexibleCell       no
useConstantRatio      no

langevinPiston        on
langevinPistonTarget  1.01325 ;#  in bar -> 1 atm
langevinPistonPeriod  300.  
langevinPistonDecay   150.
langevinPistonTemp    $temperature

margin               1

constraints on
consexp 2
consref input/rest6.ref
conskfile input/rest6.ref
conskcol O
selectConstraints on
selectConstrX off
selectConstrY off
selectConstrZ on


colvars              on
colvarsConfig        US-Z.in

