
source AmtB-remd.conf
source [format output/AmtB-A.job2.restart1500.tcl ""]
set num_runs 2000

# prevent VMD from reading umbrella.namd by trying command only NAMD has
if { ! [catch numPes] } { source ./umbrella-mod_AmtB.namd }

