
source AmtB-remd.conf
source [format output/AmtB-A.job3.restart2000.tcl ""]
set num_runs 2500

# prevent VMD from reading umbrella.namd by trying command only NAMD has
if { ! [catch numPes] } { source ./umbrella-mod_AmtB.namd }

