################################################################################################
### Script to run NAMD-Energy Plugin of VMD   (VERY INEFFICIENT)								
# NOTE: This is very inefficient, especially for large trajectories
#
# 		USE namd_energy.tcl FOR MOST CASES
#
# --------------------------------------------------
# -> Calculates Energies (Forces) on a subset of the system (due to itself/any other parts)    
# -> Calculate self and cross interaction energies of a subset of the system			          
###############################################################################################

## USAGE --------------------------------------------------
# 0: First run normal simulation to obtain .dcd trajectory
# 1. Copy script to working dir
# 2. INPUT: Set input strcuture (.psf) and frames (.dcd, .pdb, .coor)
# -------------------
# 3. INPUT: Set lists => selection 1, Selection 2 (Optional), energies, out_file_prefixes
# -> Corresponding elements of each list (sel-1, sel-2, energy, out_file) form a single calculation. 
# -> Each calculation is independent
# -------------------
# 4. set other input and output params [search for todo]
# 5. run with "vmd -dispdev text -e namd_energy_vmd_plugin.tcl"


# NAMD Command
set namd_cmd		"$::env(NAMD_MULTICORE)/namd3 +p3";	# todo: ESCAPE SPECIAL CHARACTERS like $ ! etc

# =============================
# INPUT
# =============================
# todo: [OPTIONAL] Force-Field Parameter files
set param_files	{ "../../common/ff/par_all36m_prot.prm" "../../common/ff/toppar_water_ions.prot.str" };

# todo: input strcuture file (.psf)
set psf_file		"../../common/amyl_wb.psf";

# todo: LIST of frames (.dcd, .pdb, .coor) separated by space
set frame_files	{ "../amyl_wb_eq2.dcd" "../amyl_wb_eq3.dcd" };		

# Selections
# => SEL-1 is required
# => SEL-2 is optional [CORRESPONDING TO SEL 1]. MUST NOT overlap with SEL-1
# 	1. ONLY SEL-1 		 =>  Its self energy is calculated (useful for heat capacity etc)
# 	2. BOTH SEL-1 and 2  =>  SEL-1 <-> 2 cross-interaction energy is calculated  
set selection1	{ "protein" "water" "protein" };
set selection2	{ "" 		"" 		"water" };		# corresponding to selection-1

## Output file names (CORRESPONDING TO each selection-pair)
set out_file_prefixes  { "prot_self" "water_self" "prot_water" };		# todo

### Energies to calculate (CORRESPONDING TO each selection-pair)
# OPTIONS: -bond -angl -dihe -impr -conf -vdw -elec -nonb -all
# ONLY -vdw -elec -nonb  are allowd when SEL-2 is defined
# -> -conf (confomational) = bond + angle + dihedral + improper
# -> -nonb (non-nonded) = elec + vdw
set out_energies			{ "-all" "-all" "-nonb" };

## Params
set temperature			300;		# Temperature (in K) used for main simulation [-T]
set cutoff				12;		# Cutoff distance (in Å)		[-cutoff]
set switchdist			10;		# Switch distance (in Å) for non-bonded interactions [-switch]
								#   Normally < cutoff. -ve to turn off switching
set dielectric			1.0;		# Dielectric constant (> 1 will lessen the electrostatic forces)
								
## Periodic [OPTIONAL]
set initial_ext_sys		"../amyl_wb_eq1.restart.xsc";		# [ONLY PERIODIC todo] Initial cell dimensions in .dcd file
set pme					on;		# [on/off] [ONLY PERIODIC] PME for long-range electrostatics. Only work when <initial_ext_sys> is specified

## todo: TIme Step parameters (ONLY USED FOR OUTPUT COLUMNS, DOES NOT AFFECT CALCULATION)
set timestep				1;		# Timestep (in femto-seconds)  			[-timemult]
set timestep_first		0;		# First timestep.						[-ts]
set frame_freq			200;	# Timesteps b/w each frame = dcdfreq		[-stride]

set update_sel_each_frame	off;		# [on/off] Update selection every frame		[-updatesel]

# ==================================
# OUTPUT Params			
# ==================================

## Force Output	(ONLY APPLICABLE when SEL-2 is defined)
# -> Calculates force on SEL-1 due to SEL-2
set out_force			on;		# [on/off] show force b/w two selections. [-keepforce]
set out_force_proj		off;		# [on/off] Only show projection of force on the vector connecting COM of two selections. [-projforce].  [output force will be signed (+ve: replusive, -ve attractive)]
								
set frame_skip			0;		# Calculate energy every <frame_skip> frame [-skip]

set only_gen_namd_conf		off;		# [on/off] Only generate namd configuration, DO NOT RUN simulation  [-norun]


# ==================================
# MAIN
# ==================================

# Creating namd execution script
set namd_sh_filename		"namd-exec-temp.sh";		# NAMD exe script (auto-generate with parameters)
set namd_sh_file		[open $namd_sh_filename "w"];
puts $namd_sh_file "#\!/bin/sh";			# shebang!
puts $namd_sh_file "## Generated by namd_energy_plugin.tcl for executing namd with parameters"; # Comment
puts $namd_sh_file "$namd_cmd \"\$@\"";	# namd command
flush $namd_sh_file;
close $namd_sh_file;

chmod +x $namd_sh_filename;	# make it executable

# params
set param_cmd "";
foreach p $param_files {
	set param_cmd "$param_cmd -par $p";
}

# periodic
set periodic_cmd		"";
if {[info exists initial_ext_sys] && [string trim $initial_ext_sys] ne ""} {
	set periodic_cmd "-extsys $initial_ext_sys";
}

if {[info exists pme] && [string trim $pme] eq "on"} {
	set periodic_cmd "$periodic_cmd -pme";
} 

# Others
set time_cmd		"-timemult $timestep -ts $timestep_first -stride $frame_freq";
set sim_cmd		"-T $temperature -cutoff $cutoff -switch $switchdist -diel $dielectric -skip $frame_skip";

if {[info exists update_sel_each_frame] && [string trim $update_sel_each_frame] eq "on"} {
	set sim_cmd	"$sim_cmd -updatesel";
}

if {[info exists out_force] && [string trim $out_force] eq "on"} {
	set sim_cmd "$sim_cmd -keepforce";
	
	if {[info exists out_force_proj] && [string trim $out_force_proj] eq "on"} {
		set sim_cmd "$sim_cmd -projforce";
	}
} 

if {[info exists only_gen_namd_conf] && [string trim $only_gen_namd_conf] eq "on"} {
	set sim_cmd "$sim_cmd -norun";
} 

# Final options for command
set cmd_options	"$param_cmd $time_cmd $sim_cmd $periodic_cmd -exe ./${namd_sh_filename}";


# ==================================
# Loading Frames
# ==================================
# loading INPUT .psf and .dcd files
set mol_id [mol new $psf_file];	

foreach frame_file $frame_files {
	puts "\n---------------------------------------------"
	puts " -> Loading Frames from file : ${frame_file}"
	puts "---------------------------------------------\n"
	mol addfile $frame_file waitfor all molid $mol_id;
}

# ==================================
# Runnung for each selection Pair
# ==================================
package require namdenergy;

foreach s1 $selection1 s2 $selection2 out_erg $out_energies out_file $out_file_prefixes { 
	if { [string trim $s1] eq "" } { 
		puts "\n==================================================="
		puts "-> ERROR: NO SELECTION 1 IS DEFINED !!! Skipping..."
		puts "===================================================\n"
		continue; 	# selection 1 is required
	}
	
	if { [string trim $out_file] eq "" } { 
		puts "\n==================================================="
		puts "-> ERROR: NO OUTPUT FILE IS DEFINED FOR SELECTION \"$s1\" !!! Skipping..."
		puts "===================================================\n"
		continue; 	# Output file name is required
	}

	set sel1 [atomselect $mol_id $s1];
	set sel_cmd	"-sel $sel1";

	set has_sel2		0;
	if {[string trim $s2] ne ""} {
		if {[string trim $s2] eq [string trim $s1]} {
			puts "\n==================================================="
			puts "-> ERROR: SELECTION 1 and 2 MUST BE DIFFERENT (given \"$s1\") !!! Skipping..."
			puts "===================================================\n"
			continue; 	# Selection 2 must be different than selection 1
		}
	
		set sel2 [atomselect $mol_id $s2];
		set sel_cmd	"$sel_cmd $sel2";
		set has_sel2		1;
	}
	
	# Output energies parsing
	set erg $out_erg;
	if { [string trim $erg] eq "" || [string trim $erg] eq "-all"} {
		if { $has_sel2 == 1 } { 
			set erg "-nonb";		# Only non-bonded allowed   
		} else {
			set erg "-all";
		}
	}
	
	# Output Files
	set out_erg_file				"${out_file}.energy.csv";		# Output file storing energy, force etc
	set out_temp_file_prefix		"${out_file}.namd";			# temp file for namd
	set out_cmd		"-ofile $out_erg_file -tempname $out_temp_file_prefix";

	# -------------------------------------------------------
	puts "\n==================================================="
	puts " -> Running NAMD-Energy Plugin"
	puts " -> Selection 1: \"$s1\" | Selection 2: \"$s2\" | Energies: \"$erg\" | Output: \"$out_file\""
	puts "===================================================\n"
	
	# Execute NAMD Energy Plugin
	eval "namdenergy $erg $sel_cmd $cmd_options $out_cmd";
	# -------------------------------------------------------

}

# Celaning Up
mol delete $mol_id;
rm $namd_sh_filename;

exit;
